### PR TITLE
Add deployment scripts for serving behind nginx & dnsmasq

### PR DESCRIPTION
**Pull request by 121GWJolt**
Adding initial set of deployment scripts that will allow people to run on a network using NGINX and dnsmasq. These configuration files should sort out a template for anyone looking to run it off of a Raspberry Pi or other Debian-based machine, though life has kept me from finishing the full install script.

I've had it for a while, but life happened and I only cleaned this up for today in-between doing other things. Once this PR is cleared I might be a bit before I get in more. However, at least can confirm this configuration is stable and works well!
This was tested behind an existing Wireguard VPN, though I have not tested everything (the CDN also didn't get downloaded over it, yet)

Dependencies:
- nodeJS, v20+
- NGINX
- dnsmasq
- systemd
- Open TCP ports 80, 443 (NGINX will proxy the actual UI as well)

Contains:
- SSL certificate generation script (both .bat and .sh)
- CNF file (There's a "WF" country code and I am making everyone use it)
- .gitignore so that the generated ssl folder won't ever get accidentally committed
- Utility script to hold common functions (more coming later, see below)
    - Automatically makes everything in .env available as vars for the scripts, because the syntax worked out
    - NOTE: This and the SSL script are currently coded to be as compliant with POSIX standards as possible so that as many systems as possible can run it. This one does not have a shebang at the top because in case of being run under bash it'll have an easier time finding StarPoint's root directory
- dnsmasq config
- NGINX config
    - Currently assumes that starpoint runs under port 8000, change as needed locally
- build script (temporary, going to be part of the install and run scripts later on instead)
- Systemd service

Please check the files before using them, some of them need manual fill-ins because you need to hard-code IPs and directory paths!

### CODE REVIEW

**Comment by 121GWJolt** [comment]
Still in the works:
- Bash shell script for launching, in the same format as the start.bat
    - I don't have a mac, but I'll attempt to make something Mac users should be able to run, too (*Concrete of AK voice* "POSIX, bayyy-be!")
- Full install script for those utilizing a nginx/dnsmasq setup
    - Should also install dependencies for those with apt available (I don't know any other package managers, sorry!)
    - Other DNS providers (coredns (ofc), unbound, etc.)
    - Might be able to take config values and auto-fill them into the files that normally need to be hard-coded
- Cleaning up the scripts after they're all done, because I probably should
- Docker images (*distant* TODO since I'm still learning Docker, but the idea would be to get it self-contained)
- If I get really bored/want to suffer: attempt to get everything to run under Termux
    - Purely theoretical, but termux can run python & node. Dunno what to do about CoreDNS, but it would be interesting
- If I REALLY want to suffer: learn mobile app dev and get an app to run Starpoint (via nodejs embed, I've seen it done) and run the VPN itself. 
    - I have no idea which of these two would be harder, and I'm not sure I'll ever have time to find out

**Comment by 121GWJolt** [comment]
Please note: discouraging public hosting at this time for MULTIPLE reasons.

**Comment by Duosion** [comment]
Awesome, thank you for your contribution. This is extremely useful for anyone hosting Starpoint on Linux platforms!

**Comment by 121GWJolt** [comment]
Ah, and of course I didn't forget the mitmproxy config stuff would also still be useful on Linux for those not already running their own Wireguard VPN! I might try to get that working with pip for a quick-deploy on Linux kinda thing, but I'll figure that out later.

Also, if there are problems, make sure your ip-tables have the right ports open and your system has network forwarding enabled, cuz that (and DNS) was my issue every time LOL

**Pull request merged**
